layout_spectrum: 0.93262
color:
  saturation: 0.456547
  lightness: 0.8096402
  brandStrength: 0.2022059
  brandColors:
    - '#FFFFFF'
    - '#7D7E7F'
    - '#414342'
    - '#0070AD'
    - '#BDBEBD'
  rhythmicContrast: 0.8147943
typography_spectrum: 0.8455625
name: Cauda Equina
